name: 🐛 错误报告 | Bug Report
description: 请详细描述您使用过程中遇到的问题。| Please describe in detail the problems you encountered in the process of using.
title: "[Bug问题]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        报告！我发现了一个了不得的 bug ！
  - type: input
    id: contact
    attributes:
      label: docker镜像版本
      description: 你当前使用的镜像版本，可在MusicTagWeb 项目系统设置-系统信息中查看。
      placeholder: 请填写镜像版本，如：2.2.5 或 lastet（更新时间）
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
      default: 0
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: bug 描述
      description: 请描述你怎么遇到的 bug，和 bug 的现象?
      placeholder: 请输入描述!
      value: "A bug happened! xxx"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: 系统日志（可填）
      description: 请提供系统日志.
      render: shell
