name: 🚀 功能请求 | Feature Request
description: 请详细描述您使用过程中遇到的问题。| Please describe in detail the problems you encountered in the process of using.
title: "【功能请求】: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        我有一个好的功能建议想向你提供。
  - type: textarea
    id: what-happened
    attributes:
      label: bug 描述
      description: 请描述你怎么遇到的 bug和出现什么现象被你认为是bug?
      placeholder: 请输入描述!
      value: "1.\n2.\n3"
    validations:
      required: true

